### PR TITLE
FEAT Optimize map + add clustering

### PR DESCRIPTION
**Pull request by kilowatt-**
**What type of change did you make?**
Either:
- feat

**Changes**

1. Modified map icons to use PNG for better performance
2. Added clustering to map

**Screenshots:**
image
image

Video demo : https://streamable.com/dm3b2x

**Link to Trello Card (if applicable):**
https://trello.com/c/Q5BMWLmp/6-cluster-markers-on-map
https://trello.com/c/LEGbD3WY/36-set-google-maps-markers-to-use-png-instead-of-svg

**Checklist:**

- [x] My changes don't break anything
- [x] I have removed all console logs
- [x] I have applied prettier before pushing

Mention someone for review
@sidharrth2002 
@Shaunmak1214

### CODE REVIEW

**Comment by sidharrth2002** [comment]
Looks good, maybe we can only cluster the SOS reports and reduce opacity on foodbank markers. I tried using this config
```
<GoogleMap
          mapContainerStyle={mapContainerStyle}
          zoom={8}
          center={center}
          onLoad={onLoad}
          onUnmount={onUnmount}
          options={options}
          onClick={() => {
            setModalVisible(false);
            setFoodbankModalVisible(false);
          }}
        >
          <MarkerClusterer maxZoom={12} ignoreHidden={true}>
            {(clusterer) => {
              const sosMarkers = flags.map((flag, index) => {
                return (
                  <Marker
                    visible={showSOS}
                    key={index}
                    clusterer={clusterer}
                    position={{
                      lat: parseFloat(flag.lat),
                      lng: parseFloat(flag.lng),
                    }}
                    icon={{
                      url: BDGraphics.SirenIconPNG,
                      scaledSize: new window.google.maps.Size(30, 30),
                      origin: new window.google.maps.Point(0, 0),
                      anchor: new window.google.maps.Point(15, 15),
                    }}
                    options={{
                      optimized: true,
                    }}
                    onVisibleChanged={() => {
                      if (index + 1 === flags.length) {
                        clusterer.repaint();
                      }
                    }}
                    onClick={() => {
                      setSelectedMarker(flag);
                      setFoodbankModalVisible(false);
                      setModalVisible(true);
                    }}
                  />
                );
              });
              return sosMarkers;
              // const foodbankMarkers =

              // return sosMarkers.concat(foodbankMarkers);
            }}
          </MarkerClusterer>
          {foodbanks.map((foodbank, index) => {
            return (
              <Marker
                // clusterer={clusterer}
                opacity={0.5}
                visible={showFoodbanks}
                key={index + flags.length + 1}
                position={{
                  lat: parseFloat(foodbank.address[0].coordinates.latitude),
                  lng: parseFloat(foodbank.address[0].coordinates.longitude),
                }}
                icon={{
                  url: BDGraphics.FoodBankIconPNG,
                  scaledSize: new window.google.maps.Size(15, 15),
                  origin: new window.google.maps.Point(0, 0),
                  anchor: new window.google.maps.Point(10, 10),
                }}
                options={{
                  optimized: true,
                }}
                // onVisibleChanged={() => {
                //   if (index + 1 === foodbanks.length) {
                //     clusterer.repaint();
                //   }
                // }}
                onClick={() => {
                  setSelectedFoodbank(foodbank);
                  setModalVisible(false);
                  setFoodbankModalVisible(true);
                }}
              />
            );
          })}
        </GoogleMap>

```
Screenshot 2021-07-20 at 9 46 36 PM

**Comment by kilowatt-** [comment]
@sidharrth2002 @Shaunmak1214 

I personally think that leaving the foodbanks out of the `ClusterMarker` component makes things look very messy. So, not sure if we want to do this.

Also I don't know how what would be a good different cluster image for the foodbanks.

I think we should keep it as it is - I don't see how including the foodbanks in the cluster number count is misleading, since our app is made to connect both foodbanks and people who need help if I am not mistaken; furthermore, any confusion will be cleared up once the user zooms in.

Of course, I'm happy to disagree but commit if the majority feels that we should separate foodbanks from the SOS cluster, but this is what I think

**Comment by sidharrth2002** [comment]
> @sidharrth2002 @Shaunmak1214 
> 
> I personally think that leaving the foodbanks out of the `ClusterMarker` component makes things look very messy. So, not sure if we want to do this.
> 
> Also I don't know how what would be a good different cluster image for the foodbanks.
> 
> I think we should keep it as it is - I don't see how including the foodbanks in the cluster number count is misleading, since our app is made to connect both foodbanks and people who need help if I am not mistaken; furthermore, any confusion will be cleared up once the user zooms in.
> 
> Of course, I'm happy to disagree but commit if the majority feels that we should separate foodbanks from the SOS cluster, but this is what I think

I agree that it's a bit messy if we separate but I'm only worried about people thinking the report numbers are huge at first sight

**Comment by kilowatt-** [comment]
> > @sidharrth2002 @Shaunmak1214
> > I personally think that leaving the foodbanks out of the `ClusterMarker` component makes things look very messy. So, not sure if we want to do this.
> > Also I don't know how what would be a good different cluster image for the foodbanks.
> > I think we should keep it as it is - I don't see how including the foodbanks in the cluster number count is misleading, since our app is made to connect both foodbanks and people who need help if I am not mistaken; furthermore, any confusion will be cleared up once the user zooms in.
> > Of course, I'm happy to disagree but commit if the majority feels that we should separate foodbanks from the SOS cluster, but this is what I think
> 
> I agree that it's a bit messy if we separate but I'm only worried about people thinking the report numbers are huge at first sight

Hmm. We could use the existing icons, but fix the colours for foodbanks and SOS requests respectively - what do you think?

Maybe red for SOS and green for foodbanks?

**Comment by sidharrth2002** [comment]
> > I agree that it's a bit messy if we separate but I'm only worried about people thinking the report numbers are huge at first sight
> 
> Hmm. We could use the existing icons, but fix the colours for foodbanks and SOS requests respectively - what do you think?
> 
> Maybe red for SOS and blue for foodbanks?

I'll do some research on this. Do you want to ask for suggestions in the community channel? A very specific UI UX issue

**Comment by sidharrth2002** [comment]
> > I agree that it's a bit messy if we separate but I'm only worried about people thinking the report numbers are huge at first sight
> 
> Hmm. We could use the existing icons, but fix the colours for foodbanks and SOS requests respectively - what do you think?
> 
> Maybe red for SOS and blue for foodbanks?

If we can control the colour, it's perfect

**Comment by kilowatt-** [comment]
> I'll do some research on this. Do you want to ask for suggestions in the community channel? A very specific UI UX issue

Sure I'm down to ask for suggestions especially from our designers

> If we can control the colour, it's perfect

We can control colour and size.

**Comment by sidharrth2002** [comment]
> > I'll do some research on this. Do you want to ask for suggestions in the community channel? A very specific UI UX issue
> 
> Sure I'm down to ask for suggestions especially from our designers
> 
> > If we can control the colour, it's perfect
> 
> We can control colour and size.

got it

**Comment by sidharrth2002** [comment]
Had a look at the code, will merge for now until we think of a better UI/colour separation etc.!

**Pull request merged**
