### PR TITLE
FEAT added pagination to food banks

### PR DESCRIPTION
**Pull request by Ronald545**
added pagination and fake loading animation to food banks

https://user-images.githubusercontent.com/63299413/125552984-17526a2a-8a84-4fdd-9be7-d84e0f975214.mov

[x] my change doesn't break anything

@sidharrth2002

### CODE REVIEW

**Comment by sidharrth2002** [comment]
The loading icon could it be transparent and smaller?

**Comment by Ronald545** [comment]
added smaller and transparent icon @sidharrth2002

**Comment by Shaunmak1214** [comment]
Maybe we could make use of chakra spinner, skeleton component for this https://chakra-ui.com/docs/feedback/skeleton, https://chakra-ui.com/docs/feedback/spinner. I can add it if there's an agreement.

**Comment by sidharrth2002** [comment]
> Maybe we could make use of chakra spinner, skeleton component for this https://chakra-ui.com/docs/feedback/skeleton, https://chakra-ui.com/docs/feedback/spinner. I can add it if there's an agreement.

This will be cleaner yes

**Comment by sidharrth2002** [comment]
Will have a look. Thanks Ronald!

**Comment by sidharrth2002** [comment]
@Shaunmak1214 if you're free, could you check if this is good to merge?

**Comment by Shaunmak1214** [comment]
@sidharrth2002 will do it tonight yeah, sorry for the delay

**Comment by sidharrth2002** [comment]
In favour of Chakra spinner and the PR becoming stale, will put on the backburner for now.

**Pull request closed without merging**
